# Generated by Django 4.2.4 on 2023-09-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('course_desc', models.TextField(max_length=300)),
                ('course_photo', models.CharField(max_length=150)),
                ('course_price', models.IntegerField(default=0)),
                ('course_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=30)),
                ('section_course_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('sub_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_section_title', models.CharField(max_length=30)),
                ('sub_section_desc', models.TextField(max_length=300)),
                ('sub_section_video', models.CharField(max_length=150)),
                ('sub_section_course_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('sub_section_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.section')),
            ],
        ),
    ]
